name: Publish Packages
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  verify-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test
  publish-npm:
    needs: verify-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run compile
      # Publish to npm
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
  publish-gpr:
    needs: verify-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@emandm'
      # Publish to GitHub Packages
      - run: npm ci
      - run: npm run compile

      - name: Update Package Name
        run: |
          sed -i 's,"name": "ts-mock-imports","name": "@emandm/ts-mock-imports",' package.json
          cat package.json

      - run: echo registry=https://npm.pkg.github.com/emandm >> .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
