name: Publish Packages
on:
  release:
    types: [published]

jobs:
  verify:
    runs-on: ubuntu-latest
    outputs:
      do_dry_run: ${{ steps.variables.outputs.is_dry_run }}
      environment: ${{ steps.variables.outputs.env }}
      npm_package_version: ${{ steps.set_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test
      - id: variables
        run: |
          echo "env=dry-run" >> $GITHUB_OUTPUT
          echo "is_dry_run=--dry-run" >> $GITHUB_OUTPUT
          echo "current_version=$(npm show ts-mock-imports version)" >> $GITHUB_OUTPUT
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "env=production" >> $GITHUB_OUTPUT
            echo "is_dry_run=" >> $GITHUB_OUTPUT
          fi
      - id: semver
        uses: matt-usurp/validate-semver@v2
        with:
          version: ${{ github.event.release.tag_name }}
      - id: set_version
        run: echo "version=${{ steps.semver.outputs.version }}" >> $GITHUB_OUTPUT
      - run: echo "Creating release for ts-mock-imports at version ${{ steps.semver.outputs.version }} with  ${{ steps.variables.outputs.is_dry_run }}. Current version is ${{ steps.variables.outputs.current_version }}."

  update_version:
    runs-on: ubuntu-latest
    needs: verify
    environment: ${{ needs.verify.outputs.environment }}
    if: ${{ needs.verify.outputs.environment == 'production' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          date > generated.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          npm version ${{ needs.verify.outputs.npm_package_version }}
          git push && git push --tags

  publish-npm:
    needs: [verify, update_version]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.verify.outputs.do_dry_run }}
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run compile
      # Publish to npm
      - run: npm publish --access public ${{ needs.verify.outputs.do_dry_run }} --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}

  publish-gpr:
    needs: [verify, update_version]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.verify.outputs.do_dry_run }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@emandm'
      # Publish to GitHub Packages
      - run: npm ci
      - run: npm run compile

      - name: Update Package Name
        run: |
          sed -i 's,"name": "ts-mock-imports","name": "@emandm/ts-mock-imports",' package.json
          cat package.json

      - run: echo registry=https://npm.pkg.github.com/emandm >> .npmrc
      - run: npm publish ${{ needs.verify.outputs.do_dry_run }} --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
