name: Setup Release
on:
  workflow_dispatch:
    inputs:
      semver_type:
        description: "What semver type is this release?"
        type: choice
        required: true
        options:
          - patch
          - minor
      prerelease:
        description: "Pre Release"
        type: boolean
        required: false

jobs:
  create-release:
    if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{secrets.DEPLOY_TO_MAIN_KEY}}
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test
      - id: update_version
        run: |
          date > generated.txt
          set -e

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [[ ${{ inputs.prerelease }} ]]; then
            new_version=$(npm version --preid=pre pre${{ inputs.semver_type }})
          else
            new_version=$(npm version ${{ inputs.semver_type }} )
          fi
          echo "Created version ${new_version}"

          git push && git push --tags

          echo "version_number=$new_version" >> $GITHUB_OUTPUT

      - id: pack_tar
        run: |
          npm run build
          echo "tar_name=$(npm pack)" >> $GITHUB_OUTPUT

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ steps.pack_tar.outputs.tar_name }}"
          tag: "${{ steps.update_version.outputs.version_number }}"
          generateReleaseNotes: true
          prerelease: ${{ inputs.prerelease }}
